### ISSUE TITLE
Remove `sorbet-runtime` dependency

### ISSUE THREAD

**Issue by dzunk** [workos/workos-ruby#262]
Hello, in onboarding to WorkOS we noticed that the gem has a dependency on `sorbet-runtime`. I was curious what the specific usage of that gem is, and whether or not that could be moved to a dev dependency or otherwise not be a requirement for our application.

https://github.com/workos/workos-ruby/blob/main/workos.gemspec#L24

**Comment by jasonroelofs** [comment]
We have decided to remove Sorbet from this gem. The next release will no longer have this dependency.
